# Generated by Django 5.1.5 on 2025-01-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='ports_open',
            field=models.CharField(blank=True, help_text='Liste des ports ouverts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='sondes',
            field=models.TextField(blank=True, help_text='Liste des sondes en format texte', null=True),
        ),
    ]
