# Generated by Django 5.1.5 on 2025-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0002_franchise_ports_open_franchise_sondes'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connected', max_length=20),
        ),
    ]
