# Generated by Django 5.1.5 on 2025-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0003_franchise_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='status',
            field=models.CharField(choices=[('connected', 'Connecté'), ('disconnected', 'Déconnecté')], default='connected', help_text='Statut de la franchise', max_length=20),
        ),
        migrations.AlterField(
            model_name='sondastatus',
            name='status',
            field=models.CharField(choices=[('connected', 'Connecté'), ('disconnected', 'Déconnecté')], default='connected', help_text='Statut de la sonde', max_length=20),
        ),
    ]
