# Generated by Django 5.1.5 on 2025-02-19 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0004_alter_franchise_status_alter_sondastatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Dernière mise à jour des ports/IP'),
        ),
    ]
