# Generated by Django 5.1.5 on 2025-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0005_franchise_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='status',
        ),
        migrations.AddField(
            model_name='franchise',
            name='ip_address_last_modified',
            field=models.DateTimeField(blank=True, help_text="Dernière modification de l'IP", null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='ports_open_last_modified',
            field=models.DateTimeField(blank=True, help_text='Dernière modification des ports', null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='last_modified',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour', null=True),
        ),
    ]
