# Generated by Django 5.1.5 on 2025-02-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0007_franchise_status_alter_franchise_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ip_address', models.GenericIPAddressField(blank=True, help_text='Ancienne adresse IP', null=True)),
                ('new_ip_address', models.GenericIPAddressField(blank=True, help_text='Nouvelle adresse IP', null=True)),
                ('old_ports_open', models.CharField(blank=True, help_text='Anciens ports ouverts', max_length=255, null=True)),
                ('new_ports_open', models.CharField(blank=True, help_text='Nouveaux ports ouverts', max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure du changement')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sondes.franchise')),
            ],
        ),
    ]
