# Generated by Django 5.1.5 on 2025-02-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0008_franchisechangelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='ip_address_last_modified',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='ports_open_last_modified',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='sondes',
        ),
        migrations.AlterField(
            model_name='franchise',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email du contact', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact principal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Téléphone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='last_modified',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour', null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Dernière activité'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='location',
            field=models.CharField(blank=True, help_text='Localisation', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'équipement", max_length=100)),
                ('device_type', models.CharField(choices=[('server', 'Serveur'), ('router', 'Routeur'), ('switch', 'Switch'), ('firewall', 'Pare-feu')], help_text="Type d'équipement", max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP de l'équipement")),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne')], default='online', max_length=20)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Dernière mise à jour')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to='sondes.franchise')),
            ],
        ),
    ]
