# Generated by Django 5.1.5 on 2025-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0009_remove_franchise_ip_address_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='ip_address_last_modified',
            field=models.DateTimeField(blank=True, help_text="Dernière modification de l'IP", null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='ports_open_last_modified',
            field=models.DateTimeField(blank=True, help_text='Dernière modification des ports', null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='last_modified',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour générale', null=True),
        ),
    ]
