# Generated by Django 5.1.5 on 2025-02-25 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0010_franchise_ip_address_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Adresse IP scannée')),
                ('open_ports', models.CharField(blank=True, help_text='Liste des ports ouverts', max_length=255, null=True)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure du scan')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_scans', to='sondes.franchise')),
            ],
        ),
    ]
