# Generated by Django 5.1.5 on 2025-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondes', '0011_networkscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkscan',
            name='latency',
            field=models.FloatField(blank=True, help_text='Temps de réponse en ms', null=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='os_detected',
            field=models.CharField(blank=True, help_text="Système d'exploitation détecté", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='services',
            field=models.TextField(blank=True, help_text='Services détectés sur la machine', null=True),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='vulnerabilities',
            field=models.TextField(blank=True, help_text='Liste des vulnérabilités détectées', null=True),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='open_ports',
            field=models.TextField(blank=True, help_text='Liste des ports ouverts', null=True),
        ),
    ]
